version = "V3"
id = 0
featured = false
hash = "0b778206fd9ac5ef3603633b73dba53066cbd45ded2df2955b467eead6e956e5"

[music]
id = 0
original = false
featured = false
name = "trailer"
romanized = "trailer"

[[music.authors]]
id = 0
name = "IcyLava"
romanized = "IcyLava"

[owner]
id = 1
name = "Nertsal"

[[levels]]
id = 0
name = "Hard"
authors = []
hash = "d8e721e3e2e955400206672b351d5ef62d3a1ac44ff0b3e524bd34c1afe7863b"
