version = "V3"
id = 0
featured = false
hash = "d7d4dfde03c02c3012b697ac11e1aa089e8bb1b3e830ac614c701c0f52479e6c"

[music]
id = 0
original = false
featured = false
name = "trailer"
romanized = "trailer"

[[music.authors]]
id = 0
name = "IcyLava"
romanized = "IcyLava"

[owner]
id = 1
name = "Nertsal"

[[levels]]
id = 0
name = "Hard"
authors = []
hash = "3027bdaebbd7e745775d64986de9e062eb75243d718d4f59456347bff037c5a0"
