[package]
name = "ctl-derive"
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
darling.workspace = true
proc-macro2.workspace = true
quote.workspace = true
thiserror.workspace = true
