id = 0
hash = "6998b84ef073de6014496be36eca9ed27db202e47e1cfe38d5ca2b2bb8741939"

[music]
id = 0
original = false
featured = true
name = "Gonna Terraform It!"
romanized = "Gonna Terraform It!"

[[music.authors]]
id = 0
name = "typeyourtexthereblog"
romanized = "typeyourtexthereblog"

[owner]
id = 1
name = "Nertsal"

[[levels]]
id = 0
name = "Easy"
hash = "7f8a8adf2bc66c6ddd1d01427a2a57b5de38523f03783ac7ea9fdb413561c2b0"

[[levels.authors]]
id = 1
name = "Nertsal"
romanized = "Nertsal"

[[levels]]
id = 0
name = "Normal"
hash = "f784527d8668308b3b69eb937ac1112b1ff1102fd320db040fd3dd3ed55b6694"

[[levels.authors]]
id = 1
name = "Nertsal"
romanized = "Nertsal"

[[levels]]
id = 0
name = "Hard"
hash = "1e194de2beeb6209a3e70d325a8b0ee0a4877a5ff91ea0a4a0f26f8c27f987dd"

[[levels.authors]]
id = 1
name = "Nertsal"
romanized = "Nertsal"
