[package]
name = "ctl-util"
version.workspace = true
edition.workspace = true

[dependencies]
ctl-core.workspace = true
geng.workspace = true
geng-utils.workspace = true
async-compat.workspace = true
async-executor.workspace = true
