[package]
name = "ctl-logic"
version.workspace = true
edition.workspace = true

[dependencies]
ctl-core.workspace = true
ctl-assets.workspace = true
ctl-context.workspace = true
ctl-local.workspace = true
ctl-util.workspace = true
geng.workspace = true
generational-arena.workspace = true
