[package]
name = "ctl-font"
version.workspace = true
edition.workspace = true

[dependencies]
ctl-util.workspace = true
ctl-render-core.workspace = true
geng.workspace = true
geng-utils.workspace = true
rusttype.workspace = true
